name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.bump_type }}
        echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    
    - name: Push changes
      run: |
        git push origin main
        git push origin --tags
    
    - name: Create Release PR (optional)
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "🚀 Release v${{ env.NEW_VERSION }}"
        body: |
          ## Release v${{ env.NEW_VERSION }}
          
          This PR was automatically created by the version bump workflow.
          
          ### Changes
          - Bumped version from previous to v${{ env.NEW_VERSION }}
          - Ready for release
          
          ### Next Steps
          1. Review and merge this PR
          2. The release workflow will automatically trigger
          3. Binaries will be built and published to GitHub Releases
        branch: release/v${{ env.NEW_VERSION }}
        delete-branch: true
